name: Build & Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_and_push:
    name: Build & Push to DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Get Version
        uses: entimaniac/read-pom-version-action@1.0.0
        id: getVersion
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: sergemob/procura:${{ steps.getVersion.outputs.version }}, sergemob/procura:latest

  deploy_to_server:
    runs-on: ubuntu-latest
    needs: build_and_push
    name: Deploy to Server
    steps:
      - name: Connect with SSH and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_ORACLE_HOST }}
          port: ${{ secrets.SSH_ORACLE_PORT }}
          username: ${{ secrets.SSH_ORACLE_USER }}
          key: ${{ secrets.SSH_ORACLE_KEY }}
          script: |
            mkdir -p procura
            cd procura
            mkdir -p grafana
            mkdir -p prometheus
            sudo chmod 777 grafana
            sudo chmod 777 prometheus
            git init
            git remote add origin https://github.com/serge-ponomarenko/Procura.git
            git fetch origin
            git checkout -b main --track origin/main
            git reset --hard origin/main
            git pull
            export OAUTH2_GOOGLE_CLIENT_ID=${{ secrets.OAUTH2_GOOGLE_CLIENT_ID }}
            export OAUTH2_GOOGLE_CLIENT_SECRET=${{ secrets.OAUTH2_GOOGLE_CLIENT_SECRET }}
            sudo -E docker compose stop procura
            sudo docker rm procura
            sudo docker pull sergemob/procura:latest
            sudo -E docker compose up -d
            sudo docker ps -a