name: Build & Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_and_push:
    name: Build & Push to DockerHub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Docker Build and Push to DockerHub
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: sergemob/procura:latest

  deploy_to_server:
    runs-on: ubuntu-latest
    needs: build_and_push
    name: Deploy to Server
    steps:
      - name: Connect with SSH and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            mkdir -p procura
            cd procura
            mkdir -p grafana
            mkdir -p prometheus
            sudo chmod 777 grafana
            sudo chmod 777 prometheus
            git init
            git remote add origin https://github.com/serge-ponomarenko/Procura.git
            git fetch origin
            git checkout -b main --track origin/main
            git pull
            export OAUTH2_GOOGLE_CLIENT_ID=${{ secrets.OAUTH2_GOOGLE_CLIENT_ID }}
            export OAUTH2_GOOGLE_CLIENT_SECRET=${{ secrets.OAUTH2_GOOGLE_CLIENT_SECRET }}
            sudo -E ~/.docker/cli-plugins/docker-compose stop procura
            sudo docker rm procura
            sudo docker pull sergemob/procura:latest
            sudo -E ~/.docker/cli-plugins/docker-compose up -d
            sudo docker ps -a